# Generated by Django 5.1 on 2024-08-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebbmodel',
            name='bias',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hebbmodel',
            name='weights',
            field=models.BinaryField(),
        ),
    ]
