# Generated by Django 5.1 on 2024-08-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebb', '0002_alter_hebbmodel_bias_alter_hebbmodel_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebbmodel',
            name='weights',
            field=models.JSONField(default=list),
        ),
    ]
